# Tutorial básico de Julia

## Julia II


> Ricardo Méndez Fragoso $\mathbb{R}i \vec c \hbar$
>
> Agradecimiento especial a Diego Alberto Olvera Millán por iniciar este tutorial que se ha ido actualizando a lo largo del tiempo.


# Ciclos y condicionales en Julia

Los ciclos y los condicionales son una de las herramientas más importantes al momento de programar. Los condicionales suelen tener la forma: `si [esto es cierto] entonces [haz esto] y si no [haz esto otro]` y los ciclos suelen tener la forma:  `mientras [esto sea cierto] [haz esto]`.

## Variables booleanas

Empecemos por hablar un poco acerca de las variables del tipo booleanas (`Bool`). Estas variables sólo pueden tomar dos clases de valores, cierto o falso. Veamos:

In [1]:
1>5

false

In [2]:
typeof(1>5)

Bool

Una de las formas más usuales en las que se obtienen las variables booleanas es haciendo comparaciones con los operadores:

```julia
< 
>
<=
>=
==
!=
``` 

Utiliza `?` para aprender que hace cada una de estos operadores. Observe que el operador `!` es el operador de negación:

In [3]:
!(true)

false

In [4]:
!(false)

true

## Rangos 

Ahora mencionaremos lo que es un rango (`Range`). 

In [5]:
typeof(1:5)

UnitRange{Int64}

Un rango es algo parecido a un arreglo, pero a veces resulta más eficiente para la computadora trabajar con los rangos. Se trata de un conjunto de números sobre los cuales se puede realizar una iteración. La sintaxis usual al definir un rango es:

```julia
p:h:f
```

donde `p` es el número donde empieza el rango, `h` es el tamaño de paso y `f` es el final del rango. Si queremos convertir un rango en un arreglo usamos la función `collect`:

In [6]:
collect(1:.5:2)

3-element Array{Float64,1}:
 1.0
 1.5
 2.0

Otra forma muy útil de construir rangos es con la función `linspace`, cuya sintaxis es la siguiente:

```julia 
linspace(incio, final, n=50)
``` 

Esta función construye un rango con `p=inicio`, `f=final` y `h=(final-inicio)/n`. 

## If, else 

Los ciclos y los condicionales funcionan evaluando alguna expresión booleana que tomará el valor verdadero o falso y procederá de acuerdo a esa evaluación. Veamos un ejemplo.

In [7]:
if 1>5
    print("Uno es mayor que cinco")
else
    print("Uno es menor que cinco")
end

Uno es menor que cinco

Analicemos la sintaxis. El condicional se empieza escribiendo `if`, al lado del `if` ponemos la expresión booleana (condición) que se va a evaluar y resultará en un verdadero o un falso. Después presionamos `enter` y Julia automáticamente pone una sangría para indicar que eso es el cuerpo de lo que está dentro del `if`. Ahí escribimos el conjunto de instrucciones que se deben ejecutar en caso de que la condición sea verdadera. Opcionalmente podemos poner un `else` que le indica a Julia que si la condición no es verdad, entonces ha de hacer otra cosa. También podemos escribir algo como

```julia
if condición
    orden
elseif otra condición 
    otra orden
else
    última orden
end
``` 

La estructura anterior responde las siguientes preguntas: ¿Qué ocurre si una condición es verdadero?, ¿Qué ocurre si la primera condición es falsa y otra condición es verdadera? y, finalmente, ¿Qué ocurre si las dos condiciones son falsas?.

## Ciclos for

Ahora veamos un ejemplo de ciclo `for`:

In [8]:
for i in 1:3
    println("Número: $i")
end

Número: 1
Número: 2
Número: 3


Vamos por partes. Primero escribimos `for` para indicar que vamos a empezar un ciclo iterativo. A continuación ponemos la variable sobre la cual se va a iterar, en este caso `i`. Luego ponemos `in` para indicar sobre que posibles valores se hará la iteración, usualmente se usa un rango pero también podríamos usar un arreglo o una tupla. Presionamos `enter` y escribimos la operación que se va a realizar en cada iteración del ciclo. En el ejemplo le pedimos a Julia que escriba en una línea el número de la iteración en la cual vamos. Después de escribir la operación le indicamos a Julia que hemos terminado de definir el ciclo escribiendo `end`. 

A veces queremos iterar sobre dos variables, por ejemplo cuando queremos llenar los elementos de una matriz vacía o sustituirlos por otros elementos. Esto es muy fácil de hacer sin necesidad de usar (explícitamente) dos ciclos `for`. Veamos un ejemplo. 

In [9]:
M=zeros(3,3)
for i in 1:3, j in 1:3
    M[i,j] = i + j
end
M

3×3 Array{Float64,2}:
 2.0  3.0  4.0
 3.0  4.0  5.0
 4.0  5.0  6.0

En este caso estamos haciendo dos ciclos for y es equivalente a que escribiéramos:

```julia
for i in 1:3
    for j in 1:3
        M[i,j] = i + j
    end
end
``` 

Ahora un ejemplo de un ciclo `for` que itere sobre los elementos de un arreglo o de una tupla:

In [10]:
it = (1,"hola",[1,2])
for i in it
    println(i)
end

1
hola
[1, 2]


Vemos que la iteración no es necesariamente sobre números pero sí se hace en el orden en el que aparezcan los elementos de la tupla. 

In [11]:
it_2 = [rand() for i in 1:3]
for i in it_2
    println(i)
end

0.11302585169555424
0.7629449040581373
0.1712353190184719


Nos damos un momento para explicar el arreglo `it_2` que ha sido creado con un ciclo por compresión. Este arreglo se construyó poniendo entre corchetes un ciclo `for`. Lo que esto hace es que inicia un arreglo vacío y le agrega lo que diga antes del `for` mientras el ciclo dure. En el ejemplo nos dá un número aleatorio mientras `i` va iterando del $1$ al $3$ con saltos de tamaño $1$, lo cual nos deja con un arreglo de 3 elementos. Esta es otra forma útil de usar el ciclo `for`. Podemos escribir la matriz `M` de ejemplos anteriores del mismo modo: 

In [12]:
M = [i+j for i in 1:3,j in 1:3]

3×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6

Ahora es un buen momento de ver un ejemplo de las cosas que en realidad queremos aprender a hacer. Consideremos la función factorial:

$$
n! = 1·2·...·(n-1)·n
$$

En Julia podemos evaluar $n!$ usando la función `gamma` o la función `factorial`, pero vamos a escribir una función que lo calcule. 

In [13]:
function fact(n)
    x=1
    for i in 2:n
        x=x*i
    end
    x
end

fact (generic function with 1 method)

Analicemos la función. Definimos x=1, luego entramos un ciclo `for` que empieza en `2` y llega a hasta `n` en saltos de $1$. En cada paso sustituye el valor de `x` por su valor anterior multiplicado por `i` que lleva cuenta del paso de la iteración en el que vamos. Es como si escribiéramos

$$ 
x_1 = 1
$$
$$
x_{n+1} = x_n · (n+1)
$$

Cuando llegamos a `n` salimos del ciclo `for` y la función nos regresa el valor de `x` en el que se quedó, que es precisamente $n!$.

Veamos otro ejemplo similar. Recordemos que la serie de Taylor de la función exponencial es:

$$
e^x = \sum_{n=0}^\infty \frac{x^n}{n!}
$$

Ahora, la computadora (ni nadie) pude hacer esta suma infinita, así que debemos escoger una $n$ lo suficientemente grande para tener una buena aproximación al valor real. Es decir, nosotros en realidad lo que vamos a calcular es:

$$
e^x \approx \sum_{l=0}^n \frac{x^l}{l!}
$$

y si la $n$ es suficientemente grande entonces el número que obtengamos va a ser muy parecido a $e^x$. Ahora escribamos en Julia una función que haga esta aproximación hasta la $n$ que nosotros queramos.

In [14]:
function exponencial(x,n=10)
    m=1
    for i in 1:n
        m = m + x^i / factorial(i)
    end
    m
end

exponencial (generic function with 2 methods)

Se deja como ejercicio al lector ver que esta es una buena aproximación a la exponencial y entender cada línea del código. 

## Ciclos while

Ahora hablemos de los ciclos `while`. Estos son muy similares a los ciclos `for`, pero a veces no sabemos exactamente cuántos pasos vamos a tener que dar antes de salir del ciclo. Cuando sea este el caso usamos un ciclo `while`:

In [15]:
l=0
while l<3
    println("$l")
    l+=1           #Escribir l+= es equivalente a escribir l=l+1
                   #También se puede escribir l*=n para decir l=l*n 
end
l

0
1
2


3

Analicemos la sintaxis. Primero le indicamos a Julia que vamos a iniciar el ciclo escribiendo `while`. A continuación escribimos la condición que va a ser evaluada, en este caso vamos a checar que `l` tenga un valor menor a $3$. Presionamos `enter` y entramos al cuerpo del ciclo donde le decimos a Julia que hacer en caso de que la condición tenga un valor de verdad, en este caso es mostrar en que paso del ciclo vamos y luego actualizar la variable `l`. Esta última parte es muy importante porque debemos notar que si no actualizamos el valor de `l`, la condición siempre sería verdadera y entraríamos en un ciclo infinito. Esto sucede con frecuencia en los ciclos `while` así que hay que ser cuidadosos. Una vez que termina de realizar la tarea que esté en el cuerpo, se regresa a evaluar la condición otra vez para ver si va a salir del ciclo o vuelve a realizar una tarea, por ejemplo, después de la primera vuelta `l` se actualiza y pasa a valer $1$, pero $1$ sigue siendo menor que $3$ y entonces vuelve a entrar al ciclo y  sólo termina cuando `l` alcanza el valor $3$.

¿Cuándo es más conveniente usar un ciclo `while` que un `for`?. Supongamos, por ejemplo, que se nos pide que encontremos el valor de $e^x$ con un cierto error con respecto al valor que calcula la computadora. De antemano no sabemos hasta qué orden de la aproximación (valor de $n$) debemos sumar para que el resultado tenga un error menor al pedido, entonces en este caso conviene utilizar un ciclo `while`.

In [16]:
function exponencial_2(x,tolerancia)
    m=1   #En m guardaremos el valor que estamos calculando de exp(x).
    l=1   #En l guardamos el orden de la aproximación a la que hemos llegado. 
    while abs(m-exp(x)) > tolerancia #La funcion abs nos da la distancia entre m y exp(x).
        m = m + x^l / factorial(l)
        l=l+1
    end
    m,l   #Nos regresa el valor que se obtuvo y el orden en el que nos quedamos. 
end

exponencial_2 (generic function with 1 method)

Veamos cómo funciona para $e^1=e$.

> Julia tiene guardados valores como $\pi$ o $e$. Para obtener el valor de $e$ en Julia hay que escribir `\euler` y después presionar `tab`. Esto escribirá el símbolo $e$ con cursiva en el código de Julia y en consecuencia su valor.

In [17]:
ℯ

ℯ = 2.7182818284590...

Vamos a ejecutar la función `exponencial_2` con diferentes tolerancias:

In [18]:
for i in 1:5
    println(exponencial_2(1,1/10^(i)))
end

(2.6666666666666665, 4)
(2.708333333333333, 5)
(2.7180555555555554, 7)
(2.7182539682539684, 8)
(2.71827876984127, 9)


Podemos ver que para acercarnos al resultado de la computadora en $0.1$ necesitamos al menos $4$ términos de la serie y para acercarnos en $0.00001$ necesitamos $9$ términos de la serie. Esto, en principio, no lo podríamos saber de antemano y por lo tanto un ciclo `for` no nos hubiera ayudado en este problema.

Regresar a las [Herramientas](http://sistemas.fciencias.unam.mx/~rich/Herramientas/)

Curso relacionado con este notebook: [Física Computacional](http://sistemas.fciencias.unam.mx/~rich/FisComp/)

Se agradece el apoyo de los proyectos:
* PE 112919 durante el año 2020. *Actualización a la última versión de Julia. Se han agregado explicaciones y ejemplos*
* PE 105017 durante el año 2017. *Idea original*